# Generated by Django 4.2.1 on 2023-06-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='no_of_likes',
            field=models.IntegerField(default=0),
        ),
    ]
