# Generated by Django 4.2.1 on 2023-06-21 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_likepost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikePost',
            new_name='LikeProduct',
        ),
    ]
